### ISSUE TITLE
[Feature] Bukkit-API Support

### ISSUE THREAD

**Issue by fierceeo** [LoomDev/Loom#3]
Please add support for the spigot api, so people can easily switch from spigot to loom.

Thanks!

**Comment by thatgoofydev** [comment]
This is something we have already planned and really want as a feature of Loom.

But currently the Loom-API does not yet contain enough features to bridge all of the Bukkit-API functionality. Thus, this is seen as a long term goal and not something we will be focusing on in the immediate future.

Something else I should probably mention in this Issue:
Bukkit plugins that rely on NMS code to operate will never be able to run on Loom. Because we use FabricMC's Yarn mappings to rename the Minecraft source code the naming of classes, methods and fields may be differ from the Spigot (CraftBukkit) names.

**Comment by fierceeo** [comment]
Regarding the obfuscated nms, I wonder if someone could create a system that decompiles a plugin and then does something similar to what yarn does (probably use their mappings) and convert the nms to de-obfuscated nms, so it could work on loom.

**Comment by nkomarn** [comment]
We also need to consider that a lot of plugins use reflection, so simply remapping the plugin won't solve the issue if reflection is used.

At this time, I think it's best to not focus on complete NMS support and rather get the API itself working with the compatibility layer. It would be possible to later make a tool to remap plugins but we would need to specially handle reflection, which would end up being an unreasonable amount of work.

**Comment by NicosHere** [comment]
Yes, this is a long term goal.

**Comment by nkomarn** [comment]
We, as a team, no longer have interest in bringing Bukkit API support to Loom at this time. While this may change if we get enough developers to work on a compatibility layer, this is currently not something that is planned to come any time soon. Loom has continued to move farther and farther from the Bukkit API, and as such, I'm closing this issue unless someone wants to pick this up and help write a compatibility layer.
